/-
Copyright (c) 2026 Rémy Degenne. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Rémy Degenne
-/
module

public import RandomDo.Probability.Tactic
public import RandomDo.Probability.Extend
public import LeanMachineLearning.SequentialLearning.IonescuTulceaSpace

set_option linter.style.header false

/-!
# The internal draws of an algorithm, as random variables of an algorithm-environment sequence

`IsAlgEnvSeq O A Y alg env P` says that `O`, `A` and `Y` are the observations, actions and
feedbacks generated by `alg` interacting with `env`. It says nothing about *how* the algorithm
produced its actions: when `alg` comes from an `rdo` program, the draws that program makes are not
random variables of `(Ω, P)` at all.

This file adds them. Given a trace of the algorithm — one space `Ω` of internal draws, a kernel
`K n` for their law at step `n` given the history and the observation, and a readout `out n`
reconstructing the action from them, which is what `rdo_trace` produces — it builds an algorithm
whose actions are pairs `(draws, action)`, and shows that:

* projecting away the draws turns an algorithm-environment sequence for it into one for `alg`
  (`AlgTrace.isAlgEnvSeq_snd`);
* the draws have the conditional law `K n` given the history and the observation, and the action is
  `out n` of those and the draws (`AlgTrace.hasCondDistrib_trace`, `AlgTrace.action_ae_eq`).

Since the traced algorithm interacts with the same environment, LML's `isAlgEnvSeq_unique` says
its trajectory has the same law as the original. So `AlgTrace.exists_isAlgEnvSeq_trace` may be used
to replace an arbitrary `IsAlgEnvSeq` hypothesis by one on a space that also carries the draws: the
space is existentially quantified precisely because it does not matter.

## Main definitions

* `RDo.AlgTrace alg Ω`: a trace of the algorithm `alg`, with draws in `Ω`.
* `RDo.AlgTrace.algorithm`: the algorithm whose actions carry their own draws.
* `Learning.Environment.withTrace`: the environment that ignores them.

## Main results

* `RDo.AlgTrace.isAlgEnvSeq_snd`: forgetting the draws recovers an algorithm-environment sequence
  for the original algorithm.
* `RDo.AlgTrace.hasCondDistrib_trace`: the law of the draws.
* `RDo.AlgTrace.action_ae_eq`: the action is the readout of the history, the observation and the
  draws.
* `RDo.AlgTrace.exists_isAlgEnvSeq_trace`: any algorithm-environment sequence can be replaced by
  one that also carries the draws, with the same trajectory law.

-/

@[expose] public section

open MeasureTheory ProbabilityTheory Finset Learning

noncomputable section

attribute [fun_prop] measurable_up measurable_down

/-- An algorithm-environment sequence pulls back along a measure-preserving map. With
`extend_space`, this lets one add independent randomness to a space carrying such a sequence: as
a `@[transfer_forward]` lemma, it is how the hypothesis is transported to the extended space. -/
@[transfer_forward]
lemma _root_.Learning.IsAlgEnvSeq.comp_measurePreserving {𝓞 𝓐 𝓨 Ω Ω' : Type*}
    [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨] {_ : MeasurableSpace Ω}
    {_ : MeasurableSpace Ω'} {P : Measure Ω} [IsFiniteMeasure P] {P' : Measure Ω'}
    [IsFiniteMeasure P'] {O : ℕ → Ω → 𝓞} {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨}
    {alg : Algorithm 𝓞 𝓐 𝓨} {env : Environment 𝓞 𝓐 𝓨} {f : Ω' → Ω}
    (h : IsAlgEnvSeq O A Y alg env P) (hf : MeasurePreserving f P' P) :
    IsAlgEnvSeq (fun n ω ↦ O n (f ω)) (fun n ω ↦ A n (f ω)) (fun n ω ↦ Y n (f ω)) alg env P'
    where
  measurable_obs n := (h.measurable_obs n).comp hf.measurable
  measurable_action n := (h.measurable_action n).comp hf.measurable
  measurable_feedback n := (h.measurable_feedback n).comp hf.measurable
  hasCondDistrib_obs n := (h.hasCondDistrib_obs n).comp_measurePreserving hf
  hasCondDistrib_action n := (h.hasCondDistrib_action n).comp_measurePreserving hf
  hasCondDistrib_feedback n := (h.hasCondDistrib_feedback n).comp_measurePreserving hf

/-- Being an algorithm-environment sequence is invariant under pulling back along a
measure-preserving map, for measurable sequences. This is the form the `transfer` tactic uses. The
side conditions are the measurability of the sequences: when an `IsAlgEnvSeq` hypothesis `h` is
around, put `h.measurable_obs`, `h.measurable_action` and `h.measurable_feedback` in the context for
the discharger to find them. -/
@[transfer]
lemma _root_.MeasureTheory.MeasurePreserving.transfer_isAlgEnvSeq {𝓞 𝓐 𝓨 Ω Ω' : Type*}
    [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨] {_ : MeasurableSpace Ω}
    {_ : MeasurableSpace Ω'} {P : Measure Ω} [IsFiniteMeasure P] {P' : Measure Ω'}
    [IsFiniteMeasure P'] {f : Ω' → Ω} (hf : MeasurePreserving f P' P) {O : ℕ → Ω → 𝓞}
    {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨} (hO : ∀ n, Measurable (O n)) (hA : ∀ n, Measurable (A n))
    (hY : ∀ n, Measurable (Y n)) {alg : Algorithm 𝓞 𝓐 𝓨} {env : Environment 𝓞 𝓐 𝓨} :
    IsAlgEnvSeq O A Y alg env P ↔
      IsAlgEnvSeq (fun n ω ↦ O n (f ω)) (fun n ω ↦ A n (f ω)) (fun n ω ↦ Y n (f ω)) alg env P'
    where
  mp h := h.comp_measurePreserving hf
  mpr h :=
    { measurable_obs := hO
      measurable_action := hA
      measurable_feedback := hY
      hasCondDistrib_obs n :=
        (hf.hasCondDistrib_fun_comp_iff (measurable_history hO hA hY n) (hO n)).1
          (h.hasCondDistrib_obs n)
      hasCondDistrib_action n :=
        (hf.hasCondDistrib_fun_comp_iff ((measurable_history hO hA hY n).prodMk (hO n))
          (hA n)).1 (h.hasCondDistrib_action n)
      hasCondDistrib_feedback n :=
        (hf.hasCondDistrib_fun_comp_iff
          (((measurable_history hO hA hY n).prodMk (hO n)).prodMk (hA n)) (hY n)).1
          (h.hasCondDistrib_feedback n) }

namespace RDo

universe u uO uA uY uW

variable {𝓞 : Type uO} {𝓐 : Type uA} {𝓨 : Type uY} {Ω : Type uW}
  [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨] [MeasurableSpace Ω]

/-- Forget the draws carried alongside each action of a traced history. -/
def forgetTrace (n : ℕ) (h : Hist 𝓞 (Ω × 𝓐) 𝓨 n) : Hist 𝓞 𝓐 𝓨 n :=
  fun i ↦ ((h i).1, (h i).2.1.2, (h i).2.2)

@[fun_prop]
lemma measurable_forgetTrace (n : ℕ) :
    Measurable (forgetTrace (𝓞 := 𝓞) (Ω := Ω) (𝓐 := 𝓐) (𝓨 := 𝓨) n) :=
  Measurable.of_eval fun _ ↦ by unfold forgetTrace; fun_prop

/-- What a traced policy sees at step `n` — the history and the current observation — with the
draws forgotten. -/
def forgetTraceObs (n : ℕ) (p : Hist 𝓞 (Ω × 𝓐) 𝓨 n × 𝓞) : Hist 𝓞 𝓐 𝓨 n × 𝓞 :=
  (forgetTrace n p.1, p.2)

@[fun_prop]
lemma measurable_forgetTraceObs (n : ℕ) :
    Measurable (forgetTraceObs (𝓞 := 𝓞) (Ω := Ω) (𝓐 := 𝓐) (𝓨 := 𝓨) n) := by
  unfold forgetTraceObs
  fun_prop

omit [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨] [MeasurableSpace Ω] in
@[simp]
lemma forgetTrace_history {Ω₀ : Type*} (O : ℕ → Ω₀ → 𝓞) (A : ℕ → Ω₀ → Ω × 𝓐)
    (Y : ℕ → Ω₀ → 𝓨) (n : ℕ) :
    forgetTrace n ∘ history O A Y n = history O (fun n ω ↦ (A n ω).2) Y n := rfl

/-- A *trace* of an algorithm: one space `Ω` of internal draws, a kernel giving their law at each
step given the history and the observation, and a readout reconstructing the action from them.
This is what `rdo_trace` produces for an algorithm whose policy is an `rdo` program. -/
structure AlgTrace (alg : Algorithm 𝓞 𝓐 𝓨) (Ω : Type*) [MeasurableSpace Ω] where
  /-- The law of the draws the policy makes at step `n`, given the history and the observation. -/
  K : (n : ℕ) → Kernel (Hist 𝓞 𝓐 𝓨 n × 𝓞) Ω
  /-- Those are Markov kernels. -/
  [markov : ∀ n, IsMarkovKernel (K n)]
  /-- The action at step `n`, read off the history, the observation and the draws. -/
  out : (n : ℕ) → (Hist 𝓞 𝓐 𝓨 n × 𝓞) × Ω → 𝓐
  /-- `K n` and `out n` trace the policy at step `n`. -/
  hasTrace (n : ℕ) : HasTrace (⇑(alg.policy n)) (K n) (out n)

attribute [instance] AlgTrace.markov

/-- The environment a traced algorithm interacts with: the same one, reading only the action
component of each action-with-draws. -/
def _root_.Learning.Environment.withTrace (Ω : Type*) [MeasurableSpace Ω]
    (env : Environment 𝓞 𝓐 𝓨) : Environment 𝓞 (Ω × 𝓐) 𝓨 where
  obs n := (env.obs n).comap (forgetTrace n) (by fun_prop)
  feedback n := (env.feedback n).comap
    (fun p : (Hist 𝓞 (Ω × 𝓐) 𝓨 n × 𝓞) × (Ω × 𝓐) ↦ (forgetTraceObs n p.1, p.2.2)) (by fun_prop)

namespace AlgTrace

variable {alg : Algorithm 𝓞 𝓐 𝓨} {env : Environment 𝓞 𝓐 𝓨} (tr : AlgTrace alg Ω)

@[fun_prop]
lemma measurable_out (n : ℕ) :
    Measurable fun p : (Hist 𝓞 (Ω × 𝓐) 𝓨 n × 𝓞) × Ω ↦ tr.out n (forgetTraceObs n p.1, p.2) :=
  (tr.hasTrace n).measurable_out.comp
    (((measurable_forgetTraceObs n).comp measurable_fst).prodMk measurable_snd)

/-- The traced algorithm: it draws the policy's internal randomness, then reads the action off it.
Its actions are pairs `(draws, action)`. -/
def algorithm : Algorithm 𝓞 (Ω × 𝓐) 𝓨 where
  policy n :=
    (tr.K n).comap (forgetTraceObs n) (by fun_prop)
      ⊗ₖ Kernel.deterministic _ (tr.measurable_out n)

/-- Comap turns a deterministic kernel into the deterministic kernel of the composite. -/
lemma _root_.ProbabilityTheory.Kernel.comap_deterministic {α β γ : Type*} [MeasurableSpace α]
    [MeasurableSpace β] [MeasurableSpace γ] {f : α → β} (hf : Measurable f) {g : γ → α}
    (hg : Measurable g) :
    (Kernel.deterministic f hf).comap g hg = Kernel.deterministic (f ∘ g) (hf.comp hg) := by
  ext c s hs
  simp [Kernel.comap_apply, Kernel.deterministic_apply]

/-- The traced policy at a given history and observation, with the draws forgotten, is the
original policy. -/
lemma map_snd_policy_apply (n : ℕ) (h : Hist 𝓞 (Ω × 𝓐) 𝓨 n × 𝓞) :
    (tr.algorithm.policy n h).map Prod.snd = alg.policy n (forgetTraceObs n h) := by
  have hg : Measurable fun a ↦ tr.out n (forgetTraceObs n h, a) :=
    (tr.hasTrace n).measurable_out.comp (measurable_const.prodMk measurable_id)
  have hp : Measurable fun a ↦ (a, tr.out n (forgetTraceObs n h, a)) := measurable_id.prodMk hg
  change (((tr.K n).comap (forgetTraceObs n) (measurable_forgetTraceObs n)
    ⊗ₖ Kernel.deterministic _ (tr.measurable_out n)) h).map Prod.snd = _
  rw [Kernel.compProd_apply_eq_compProd_sectR, Kernel.sectR, Kernel.comap_deterministic,
    Measure.compProd_deterministic, Kernel.comap_apply]
  simp only [Function.comp_apply]
  rw [Measure.map_map measurable_snd hp]
  exact (tr.hasTrace n).map_eq (forgetTraceObs n h)

/-- Forgetting the draws of the traced policy gives back the original policy. -/
lemma snd_policy (n : ℕ) :
    (tr.algorithm.policy n).snd = (alg.policy n).comap (forgetTraceObs n) (by fun_prop) :=
  Kernel.ext fun h ↦ by
    rw [Kernel.snd_apply, Kernel.comap_apply, tr.map_snd_policy_apply n h]

variable {Ω₀ : Type*} {_ : MeasurableSpace Ω₀} {P : Measure Ω₀} [IsProbabilityMeasure P]
  {O : ℕ → Ω₀ → 𝓞} {A : ℕ → Ω₀ → Ω × 𝓐} {Y : ℕ → Ω₀ → 𝓨}

section Projection

variable (h : IsAlgEnvSeq O A Y tr.algorithm (env.withTrace Ω) P)
include h

/-- **Forgetting the draws.** An algorithm-environment sequence for the traced algorithm is, after
dropping the draws from each action, one for the original algorithm. -/
lemma isAlgEnvSeq_snd : IsAlgEnvSeq O (fun n ω ↦ (A n ω).2) Y alg env P where
  measurable_obs n := h.measurable_obs n
  measurable_action n := measurable_snd.comp (h.measurable_action n)
  measurable_feedback n := h.measurable_feedback n
  hasCondDistrib_obs n :=
    HasCondDistrib.comp_right (hf := measurable_forgetTrace n) (h.hasCondDistrib_obs n)
  hasCondDistrib_action n := by
    have h1 := (h.hasCondDistrib_action n).snd
    rw [tr.snd_policy n] at h1
    exact HasCondDistrib.comp_right (hf := measurable_forgetTraceObs n) h1
  hasCondDistrib_feedback n :=
    HasCondDistrib.comp_right (hf := by fun_prop) (h.hasCondDistrib_feedback n)

/-- **The conditional law of the draws.** Given the history and the observation, the draws the
policy makes at step `n` are distributed as `K n` — the kernel the trace of the `rdo` program
produced. -/
lemma hasCondDistrib_trace (n : ℕ) :
    HasCondDistrib (fun ω ↦ (A n ω).1)
      (fun ω ↦ (history O (fun n ω ↦ (A n ω).2) Y n ω, O n ω)) (tr.K n) P := by
  have h1 := (h.hasCondDistrib_action n).fst
  rw [algorithm, Kernel.fst_compProd] at h1
  exact HasCondDistrib.comp_right (hf := measurable_forgetTraceObs n) h1

/-- **The action is the readout of the history, the observation and the draws.** -/
lemma action_ae_eq [MeasurableEq 𝓐] (n : ℕ) :
    (fun ω ↦ (A n ω).2) =ᵐ[P]
      fun ω ↦ tr.out n ((history O (fun n ω ↦ (A n ω).2) Y n ω, O n ω), (A n ω).1) := by
  have hO := h.measurable_obs
  have hA := h.measurable_action
  have hY := h.measurable_feedback
  have h1 := (h.hasCondDistrib_action n).compProd_snd
  exact ae_eq_of_hasCondDistrib_deterministic (tr.measurable_out n)
    (X := fun ω ↦ ((history O A Y n ω, O n ω), (A n ω).1))
    (by fun_prop) (measurable_snd.comp (h.measurable_action n)).aemeasurable h1

end Projection

/-- **The draws may be assumed to be there.** Any algorithm-environment sequence for `alg` and
`env` can be replaced by one on a space that also carries the algorithm's internal draws `T`, with
the same trajectory law — so anything proved about the law of the observations, actions and
feedbacks there holds of the original. The space is existentially quantified because, by
`isAlgEnvSeq_unique`, it does not matter; it may be taken in any universe at least those of `𝓞`,
`𝓐`, `𝓨` and `Ω`.

Besides the laws of the draws and the readout equations, the actions and draws together form an
algorithm-environment sequence for the traced algorithm. This says more than the rest: the draws
at a step are conditionally independent of the earlier draws given the history, and the feedback
does not read the draws. -/
theorem exists_isAlgEnvSeq_trace [MeasurableEq 𝓐] {O₀ : ℕ → Ω₀ → 𝓞} {A₀ : ℕ → Ω₀ → 𝓐}
    {Y₀ : ℕ → Ω₀ → 𝓨} (h₀ : IsAlgEnvSeq O₀ A₀ Y₀ alg env P) :
    ∃ (Ω' : Type (max u uO uA uY uW)) (_ : MeasurableSpace Ω') (P' : Measure Ω')
      (_ : IsProbabilityMeasure P') (O : ℕ → Ω' → 𝓞) (A : ℕ → Ω' → 𝓐) (Y : ℕ → Ω' → 𝓨)
      (T : ℕ → Ω' → Ω),
      IsAlgEnvSeq O A Y alg env P'
        ∧ IsAlgEnvSeq O (fun n ω ↦ (T n ω, A n ω)) Y tr.algorithm (env.withTrace Ω) P'
        ∧ P'.map (trajectory O A Y) = P.map (trajectory O₀ A₀ Y₀)
        ∧ (∀ n, HasCondDistrib (T n) (fun ω ↦ (history O A Y n ω, O n ω)) (tr.K n) P')
        ∧ (∀ n, A n =ᵐ[P'] fun ω ↦ tr.out n ((history O A Y n ω, O n ω), T n ω)) := by
  -- The trajectory space of the traced algorithm, lifted to the universe asked for.
  let base := trajMeasure tr.algorithm (env.withTrace Ω)
  let e : ULift.{u} (ℕ → Round 𝓞 (Ω × 𝓐) 𝓨) ≃ᵐ (ℕ → Round 𝓞 (Ω × 𝓐) 𝓨) :=
    MeasurableEquiv.ulift
  have hup : MeasurePreserving e.symm base (base.map e.symm) := ⟨e.symm.measurable, rfl⟩
  have hf : MeasurePreserving e (base.map e.symm) base := hup.symm e.symm
  have htr : IsAlgEnvSeq (fun n ω ↦ IT.obs n (e ω)) (fun n ω ↦ IT.action n (e ω))
      (fun n ω ↦ IT.feedback n (e ω)) tr.algorithm (env.withTrace Ω) (base.map e.symm) :=
    (IT.isAlgEnvSeq_trajMeasure tr.algorithm (env.withTrace Ω)).comp_measurePreserving hf
  exact ⟨ULift (ℕ → Round 𝓞 (Ω × 𝓐) 𝓨), inferInstance, base.map e.symm, inferInstance,
    fun n ω ↦ IT.obs n (e ω), fun n ω ↦ (IT.action n (e ω)).2, fun n ω ↦ IT.feedback n (e ω),
    fun n ω ↦ (IT.action n (e ω)).1, tr.isAlgEnvSeq_snd htr, htr,
    isAlgEnvSeq_unique (tr.isAlgEnvSeq_snd htr) h₀, tr.hasCondDistrib_trace htr,
    tr.action_ae_eq htr⟩

/-- **The principle behind the `alg_env_trace` tactic.** To prove a statement `motive` about an
algorithm-environment sequence it is enough to prove it on a space that also carries the
algorithm's internal draws, *provided* the statement only depends on the law of the trajectory —
which is what the `transfer` hypothesis asks for, and which is exactly the freedom
`isAlgEnvSeq_unique` gives. The space may live in any universe at least those of `𝓞`, `𝓐`, `𝓨`
and `Ω`. -/
theorem wlog_trace [MeasurableEq 𝓐]
    {motive : (Ω₀ : Type (max u uO uA uY uW)) → [MeasurableSpace Ω₀] → (P : Measure Ω₀) →
      [IsProbabilityMeasure P] → (ℕ → Ω₀ → 𝓞) → (ℕ → Ω₀ → 𝓐) → (ℕ → Ω₀ → 𝓨) → Prop}
    (traced : ∀ (Ω' : Type (max u uO uA uY uW)) [MeasurableSpace Ω'] (P' : Measure Ω')
        [IsProbabilityMeasure P'] (O' : ℕ → Ω' → 𝓞) (A' : ℕ → Ω' → 𝓐) (Y' : ℕ → Ω' → 𝓨)
        (T : ℕ → Ω' → Ω),
      IsAlgEnvSeq O' A' Y' alg env P' →
      IsAlgEnvSeq O' (fun n ω ↦ (T n ω, A' n ω)) Y' tr.algorithm (env.withTrace Ω) P' →
      (∀ n, HasCondDistrib (T n) (fun ω ↦ (history O' A' Y' n ω, O' n ω)) (tr.K n) P') →
      (∀ n, A' n =ᵐ[P'] fun ω ↦ tr.out n ((history O' A' Y' n ω, O' n ω), T n ω)) →
      motive Ω' P' O' A' Y')
    (transfer : ∀ (Ω₁ : Type (max u uO uA uY uW)) [MeasurableSpace Ω₁] (P₁ : Measure Ω₁)
        [IsProbabilityMeasure P₁] (O₁ : ℕ → Ω₁ → 𝓞) (A₁ : ℕ → Ω₁ → 𝓐) (Y₁ : ℕ → Ω₁ → 𝓨)
        (Ω₂ : Type (max u uO uA uY uW)) [MeasurableSpace Ω₂] (P₂ : Measure Ω₂)
        [IsProbabilityMeasure P₂] (O₂ : ℕ → Ω₂ → 𝓞) (A₂ : ℕ → Ω₂ → 𝓐) (Y₂ : ℕ → Ω₂ → 𝓨),
      IsAlgEnvSeq O₁ A₁ Y₁ alg env P₁ → IsAlgEnvSeq O₂ A₂ Y₂ alg env P₂ →
      P₂.map (trajectory O₂ A₂ Y₂) = P₁.map (trajectory O₁ A₁ Y₁) →
      motive Ω₂ P₂ O₂ A₂ Y₂ → motive Ω₁ P₁ O₁ A₁ Y₁)
    :
    ∀ (Ω₀ : Type (max u uO uA uY uW)) [MeasurableSpace Ω₀] (P : Measure Ω₀)
      [IsProbabilityMeasure P] (O : ℕ → Ω₀ → 𝓞) (A : ℕ → Ω₀ → 𝓐) (Y : ℕ → Ω₀ → 𝓨),
      IsAlgEnvSeq O A Y alg env P → motive Ω₀ P O A Y := by
  intro Ω₀ _ P _ O A Y h
  -- The universe of the traced space is that of `Ω₀`; Lean does not solve it on its own.
  obtain ⟨Ω', mΩ', P', hP', O', A', Y', T, hseq, htr, hlaw, hT, hA⟩ :=
    tr.exists_isAlgEnvSeq_trace.{u, _, _, _, _, _} h
  exact transfer Ω₀ P O A Y Ω' P' O' A' Y' h hseq hlaw (traced Ω' P' O' A' Y' T hseq htr hT hA)

end AlgTrace


end RDo

end

end

public meta section

open Lean Lean.Meta Lean.Elab Lean.Elab.Tactic
open MeasureTheory ProbabilityTheory Learning

namespace RDo.Tactic

initialize registerTraceClass `alg_env_trace

/-- The free variables carrying the probability space of an `IsAlgEnvSeq` hypothesis: the space,
its σ-algebra, the measure, the `IsProbabilityMeasure` instance, and the three sequences. They have
to be local hypotheses, since the tactic abstracts the goal over them. -/
def algEnvSpaceFVars (hFVar : FVarId) : MetaM (Array FVarId) := do
  let ty ← instantiateMVars (← hFVar.getType)
  unless ty.isAppOf ``IsAlgEnvSeq do
    throwError "alg_env_trace: {Expr.fvar hFVar} is not an `IsAlgEnvSeq` hypothesis"
  let as := ty.getAppArgs
  let O := as[as.size - 7]!
  let A := as[as.size - 6]!
  let Y := as[as.size - 5]!
  let P := as[as.size - 2]!
  let mΩ := (← whnfR (← inferType P)).getAppArgs[1]!
  let Ω := (← whnfR (← inferType P)).getAppArgs[0]!
  let mut out : Array FVarId := #[]
  for e in #[Ω, mΩ, P] do
    let .fvar f := e | throwError
      "alg_env_trace: the probability space must be given by local hypotheses, but {e} is not"
    out := out.push f
  -- the `IsProbabilityMeasure` hypothesis, which `isAlgEnvSeq_unique` needs
  let some hP ← (do
    for d in ← getLCtx do
      if !d.isImplementationDetail then
        if (← instantiateMVars d.type) == (← mkAppM ``IsProbabilityMeasure #[P]) then
          return some d.fvarId
    return none) | throwError
      "alg_env_trace: no `IsProbabilityMeasure` hypothesis for {P} in the context"
  out := out.push hP
  for e in #[O, A, Y] do
    let .fvar f := e | throwError
      "alg_env_trace: the observation, action and feedback sequences must be local hypotheses, \
      but {e} is not"
    out := out.push f
  return out.push hFVar

/-- How many binders of `wlog_trace` come before its conclusion: up to and including its third
explicit argument, `transfer`. Everything after that belongs to the `∀`-shaped conclusion, which is
what the goal is unified with. -/
partial def preConclusionArity : Expr → Nat → Nat → Nat
  | .forallE _ _ b bi, n, e =>
    let e := if bi.isExplicit then e + 1 else e
    if e == 3 then n + 1 else preConclusionArity b (n + 1) e
  | _, n, _ => n

/-- Find an `IsAlgEnvSeq` hypothesis in the context. -/
def findAlgEnvSeq? : MetaM (Option FVarId) := do
  for d in ← getLCtx do
    if !d.isImplementationDetail then
      if (← instantiateMVars d.type).isAppOf ``IsAlgEnvSeq then return some d.fvarId
  return none

/-- `alg_env_trace tr` replaces an `IsAlgEnvSeq` situation by one in which the algorithm's internal
draws are present. `tr` is an `RDo.AlgTrace` for the algorithm — the trace of its policy, as
produced by `rdo_trace`.

The goal, together with every hypothesis about the sequence — a statement mentioning the space,
the measure or the two sequences — is abstracted away from that space and two goals are left:

* `traced`: the same statement on a space that also carries the draws `T`, with `hseq`, the
  sequence again, `htr`, actions and draws together as a sequence for the traced algorithm, `hT`,
  the conditional law of the draws given the history and the observation, and `hA`, each action as
  the readout of those and the draws;
* `transfer`: the obligation that the statement only depends on the law of the trajectory. This is
  what makes the replacement sound — the traced sequence lives on a different space, and all that
  relates it to the original is `isAlgEnvSeq_unique`. The `transfer` tactic discharges it through
  the trajectory space, onto which both sequences are measure-preserving maps, and the goal is only
  left when that fails.

Data on the space that is not the sequence — a random variable, an event, a point — has no
counterpart on the traced space: the goal may not depend on it, and it is cleared, together with
the hypotheses about it, before the change of space.

* `alg_env_trace tr using h` names the hypothesis to use rather than searching for one.
* `alg_env_trace tr with Ω P O A Y T hseq htr hT hA` names what is introduced.

The probability space, its σ-algebra, the measure, the `IsProbabilityMeasure` hypothesis and the
three sequences all have to be local hypotheses, since the goal is abstracted over them, and the
space has to live in a universe at least those of the observations, the actions, the feedbacks and
the draws. -/
syntax (name := algEnvTraceTac) "alg_env_trace" ppSpace term (" using " ident)?
  (" with " (ppSpace colGt ident)+)? : tactic

elab_rules : tactic
  | `(tactic| alg_env_trace $tr $[using $h?]? $[with $names?*]?) => withMainContext do
    let g ← getMainGoal
    let hFVar ← match h? with
      | some h => getFVarId h
      | none => match ← findAlgEnvSeq? with
        | some f => pure f
        | none => throwError "alg_env_trace: no `IsAlgEnvSeq` hypothesis in the context"
    let spaceFVars ← algEnvSpaceFVars hFVar
    let spaceSet : FVarIdSet := spaceFVars.foldl (·.insert ·) {}
    let hTy ← instantiateMVars (← hFVar.getType)
    let algE := hTy.getAppArgs[hTy.getAppNumArgs - 4]!
    -- The trajectory space `ℕ → Round 𝓞 𝓐 𝓨`, lifted to the universe of the space: the
    -- obligation is discharged through it.
    let liftTy ← do
      let 𝓞 := (← instantiateMVars (← inferType (.fvar spaceFVars[4]!))).getForallBody
      let 𝓐 := (← instantiateMVars (← inferType (.fvar spaceFVars[5]!))).getForallBody
      let 𝓨 := (← instantiateMVars (← inferType (.fvar spaceFVars[6]!))).getForallBody
      let trajTy ← mkArrow (mkConst ``Nat) (← mkAppM ``Prod #[𝓞, ← mkAppM ``Prod #[𝓐, 𝓨]])
      pure (mkApp (mkConst ``ULift [← getDecLevel (.fvar spaceFVars[0]!), ← getDecLevel trajTy])
        trajTy)
    let given := (names?.map (·.map (·.getId))).getD #[]
    let defaults : Array Name := #[`Ω, `P, `O, `A, `Y, `T, `hseq, `htr, `hT, `hA]
    if given.size > defaults.size then
      throwError "alg_env_trace: at most {defaults.size} names may be given"
    -- What else mentions the space. A statement about the sequence travels with the goal, and is
    -- pulled back to the traced space. Data on the space — a random variable, an event, a point —
    -- has no counterpart there: the goal may not depend on it, and it is cleared, together with
    -- what is about it.
    let lctx ← getLCtx
    let fvarsOf (d : LocalDecl) : MetaM (Array FVarId) := do
      let mut st := Lean.collectFVars {} (← instantiateMVars d.type)
      if let some v := d.value? then st := Lean.collectFVars st (← instantiateMVars v)
      pure st.fvarIds
    let mut props : Array FVarId := #[]
    let mut data : FVarIdSet := {}
    for d in lctx do
      if d.isImplementationDetail || spaceSet.contains d.fvarId then continue
      unless (← fvarsOf d).any spaceSet.contains do continue
      if !d.isLet && (← isProp d.type) then props := props.push d.fvarId
      else data := data.insert d.fvarId
    let mut changed := true
    while changed do
      changed := false
      for d in lctx do
        if d.isImplementationDetail || data.contains d.fvarId || spaceSet.contains d.fvarId then
          continue
        if (← fvarsOf d).any data.contains then
          data := data.insert d.fvarId
          changed := true
    let mut goalDeps : FVarIdSet := {}
    let mut todo := (Lean.collectFVars {} (← instantiateMVars (← g.getType))).fvarIds
    while !todo.isEmpty do
      let x := todo.back!
      todo := todo.pop
      if goalDeps.contains x then continue
      goalDeps := goalDeps.insert x
      todo := todo ++ (← fvarsOf (← x.getDecl))
    for d in lctx do
      if data.contains d.fvarId && goalDeps.contains d.fvarId then
        throwError "alg_env_trace: the goal depends on{indentExpr d.toExpr}\nof type{indentExpr
          (← instantiateMVars d.type)}\nwhich lives on the space of the sequence without being \
          part of it. Only statements about the actions, the feedbacks and the measure survive \
          the change of space."
    let propsKept := props.filter (!data.contains ·)
    let toClear ← sortFVarIds data.toArray
    unless toClear.isEmpty do
      trace[alg_env_trace] "cleared, as data on the space that is not the sequence: \
        {toClear.map Expr.fvar}"
    let g ← g.tryClearMany toClear
    let (propsReverted, g) ← g.revert propsKept
    let (spaceReverted, g) ← g.revert spaceFVars (preserveOrder := true)
    -- What was reverted beyond the space itself: the statements, and anything `revert` had to
    -- take along.
    let nTravelling := spaceReverted.size - spaceFVars.size + propsReverted.size
    -- Build `wlog_trace tr ?traced ?transfer` and check it proves the abstracted goal.
    let trE ← g.withContext do
      let e ← Term.elabTerm tr none
      Term.synthesizeSyntheticMVarsNoPostponing
      instantiateMVars e
    let (traced, transfer, motiveE) ← g.withContext do
      let c ← mkConstWithFreshMVarLevels ``RDo.AlgTrace.wlog_trace
      let cty ← inferType c
      let (args, bis, concl) ← forallMetaBoundedTelescope cty (preConclusionArity cty 0 0)
      let explicits := (args.zip bis).filterMap fun (a, b) ↦ if b.isExplicit then some a else none
      let some iMotive := binderIndex? cty `motive
        | throwError "alg_env_trace: `wlog_trace` no longer has a `motive` binder"
      unless explicits.size == 3 do
        throwError "alg_env_trace: `wlog_trace` no longer has the expected shape"
      unless ← isDefEq explicits[0]! trE do
        throwError "alg_env_trace: {trE} is not a trace of the algorithm of the hypothesis"
      let some iAlg := binderIndex? cty `alg
        | throwError "alg_env_trace: `wlog_trace` no longer has an `alg` binder"
      unless ← isDefEq (← instantiateMVars args[iAlg]!) algE do
        throwError "alg_env_trace: {trE} is not a trace of the algorithm of the hypothesis"
      unless ← isDefEq concl (← g.getType) do
        throwError "alg_env_trace: the goal does not have the expected shape{indentExpr
          (← g.getType)}\nThe space has to live in a universe at least those of the actions, \
          the observations, the actions, the feedbacks and the draws."
      for (a, b) in args.zip bis do
        if b.isInstImplicit && !(← a.mvarId!.isAssigned) then
          a.mvarId!.assign (← synthInstance (← instantiateMVars (← a.mvarId!.getType)))
      g.assign (mkAppN c args)
      let traced := explicits[1]!.mvarId!
      let transfer := explicits[2]!.mvarId!
      traced.setKind .syntheticOpaque
      transfer.setKind .syntheticOpaque
      traced.setTag `traced
      transfer.setTag `transfer
      return (traced, transfer, args[iMotive]!)
    -- Introduce the traced space and its properties, then whatever travelled with the goal.
    let pick (i : Nat) : Name := if h : i < given.size then given[i] else defaults[i]!
    let intros : Array Name :=
      #[pick 0, `inst, pick 1, `inst, pick 2, pick 3, pick 4, pick 5, pick 6, pick 7,
        pick 8, pick 9]
    let (_, traced) ← traced.introN intros.size intros.toList
    let (_, traced) ← traced.introNP nTravelling
    -- Discharge the transfer obligation through the trajectory space when `transfer` can: both
    -- sequences are measure-preserving maps onto `(ℕ → Round 𝓞 𝓐 𝓨, ν)`, on which the statement
    -- is proved from the second sequence, then pulled back to the first.
    let rest := (← getGoals).drop 1
    let s ← saveFullState
    let transferLeft ← tryCatchRuntimeEx
      (do
        setGoals [transfer]
        withMainContext do
          let motiveStx ← Term.exprToSyntax (← instantiateMVars motiveE)
          let liftStx ← Term.exprToSyntax liftTy
          -- Without error recovery, a failure inside a nested `by` is a failure, not a `sorry`.
          Term.withoutErrToSorry <| evalTactic (← `(tactic| (
            intro Ω₁ _ P₁ _ O₁ A₁ Y₁ Ω₂ _ P₂ _ O₂ A₂ Y₂ h₁ h₂ hlaw h
            have hlaw' : (Measure.map (trajectory O₂ A₂ Y₂) P₂).map (ULift.up : _ → $liftStx)
                = (Measure.map (trajectory O₁ A₁ Y₁) P₁).map ULift.up := by rw [hlaw]
            generalize hν : (Measure.map (trajectory O₁ A₁ Y₁) P₁).map
              (ULift.up : _ → $liftStx) = ν at hlaw'
            have hf₁ : MeasurePreserving (fun ω ↦ (ULift.up (trajectory O₁ A₁ Y₁ ω) : $liftStx))
                P₁ ν := by
              rw [← hν]
              exact (⟨measurable_up, rfl⟩ :
                  MeasurePreserving ULift.up (Measure.map (trajectory O₁ A₁ Y₁) P₁) _).comp
                ⟨measurable_trajectory h₁.measurable_obs h₁.measurable_action
                  h₁.measurable_feedback, rfl⟩
            have hf₂ : MeasurePreserving (fun ω ↦ (ULift.up (trajectory O₂ A₂ Y₂ ω) : $liftStx))
                P₂ ν := by
              rw [← hlaw']
              exact (⟨measurable_up, rfl⟩ :
                  MeasurePreserving ULift.up (Measure.map (trajectory O₂ A₂ Y₂) P₂) _).comp
                ⟨measurable_trajectory h₂.measurable_obs h₂.measurable_action
                  h₂.measurable_feedback, rfl⟩
            have : IsProbabilityMeasure ν := by
              rw [← hν]
              infer_instance
            exact (fun hS : $motiveStx _ inferInstance ν inferInstance
                (fun n (t : $liftStx) ↦ (t.down n).1) (fun n (t : $liftStx) ↦ (t.down n).2.1)
                (fun n (t : $liftStx) ↦ (t.down n).2.2) ↦
                  (by transfer hf₁ at hS; exact hS))
              (by beta_reduce; transfer hf₂))))
        unless (← getUnsolvedGoals).isEmpty do throwError "transfer left goals"
        pure [])
      (fun e ↦ do
        let msg ← (← addMessageContextFull e.toMessageData).toString
        s.restore
        trace[alg_env_trace] "the transfer obligation is left, because: {msg}"
        pure [transfer])
    setGoals ([traced] ++ transferLeft ++ rest)

end RDo.Tactic

end
