/-
Copyright (c) 2026 Rémy Degenne. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Rémy Degenne
-/
module

public import RandomDo.Probability.Tactic
public import RandomDo.Probability.Extend
public import LeanMachineLearning.SequentialLearning.IonescuTulceaSpace

set_option linter.style.header false

/-!
# The internal draws of an algorithm, as random variables of an algorithm-environment sequence

`IsAlgEnvSeq A Y alg env P` says that `A` and `Y` are the actions and feedbacks generated by `alg`
interacting with `env`. It says nothing about *how* the algorithm produced its actions: when `alg`
comes from an `rdo` program, the draws that program makes are not random variables of `(Ω, P)` at
all.

This file adds them. Given a trace of the algorithm — one space `Ω` of internal draws, a kernel
`K n` for their law at step `n`, and a readout `out n` reconstructing the action from them, which
is what `rdo_trace` produces — it builds an algorithm whose actions are pairs `(draws, action)`,
and shows that:

* projecting away the draws turns an algorithm-environment sequence for it into one for `alg`
  (`AlgTrace.isAlgEnvSeq_snd`);
* the draws have the conditional law `K n` given the history, and the action is `out n` of the
  history and the draws (`AlgTrace.hasCondDistrib_trace`, `AlgTrace.action_ae_eq`).

Since the traced algorithm interacts with the same environment, LML's `isAlgEnvSeq_unique` says
its trajectory has the same law as the original. So `AlgTrace.exists_isAlgEnvSeq_trace` may be used
to replace an arbitrary `IsAlgEnvSeq` hypothesis by one on a space that also carries the draws: the
space is existentially quantified precisely because it does not matter.

## Main definitions

* `RDo.AlgTrace alg Ω`: a trace of the algorithm `alg`, with draws in `Ω`.
* `RDo.AlgTrace.algorithm`: the algorithm whose actions carry their own draws.
* `Learning.Environment.withTrace`: the environment that ignores them.

## Main results

* `RDo.AlgTrace.isAlgEnvSeq_snd`: forgetting the draws recovers an algorithm-environment sequence
  for the original algorithm.
* `RDo.AlgTrace.hasLaw_trace_zero`, `RDo.AlgTrace.hasCondDistrib_trace`: the law of the draws.
* `RDo.AlgTrace.action_zero_ae_eq`, `RDo.AlgTrace.action_ae_eq`: the action is the readout of the
  history and the draws.
* `RDo.AlgTrace.exists_isAlgEnvSeq_trace`: any algorithm-environment sequence can be replaced by
  one that also carries the draws, with the same trajectory law.

-/

@[expose] public section

open MeasureTheory ProbabilityTheory Finset Learning

noncomputable section

/-- An algorithm-environment sequence pulls back along a measure-preserving map. With
`extend_space`, this lets one add independent randomness to a space carrying such a sequence: as
a `@[transfer_forward]` lemma, it is how the hypothesis is transported to the extended space. -/
@[transfer_forward]
lemma _root_.Learning.IsAlgEnvSeq.comp_measurePreserving {𝓐 𝓨 Ω Ω' : Type*} [MeasurableSpace 𝓐]
    [MeasurableSpace 𝓨] {_ : MeasurableSpace Ω} {_ : MeasurableSpace Ω'} {P : Measure Ω}
    [IsFiniteMeasure P] {P' : Measure Ω'} [IsFiniteMeasure P'] {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨}
    {alg : Algorithm 𝓐 𝓨} {env : Environment 𝓐 𝓨} {f : Ω' → Ω}
    (h : IsAlgEnvSeq A Y alg env P) (hf : MeasurePreserving f P' P) :
    IsAlgEnvSeq (fun n ω ↦ A n (f ω)) (fun n ω ↦ Y n (f ω)) alg env P' where
  measurable_action n := (h.measurable_action n).comp hf.measurable
  measurable_feedback n := (h.measurable_feedback n).comp hf.measurable
  hasLaw_action_zero := h.hasLaw_action_zero.comp hf.hasLaw
  hasCondDistrib_feedback_zero := h.hasCondDistrib_feedback_zero.comp_measurePreserving hf
  hasCondDistrib_action n := (h.hasCondDistrib_action n).comp_measurePreserving hf
  hasCondDistrib_feedback n := (h.hasCondDistrib_feedback n).comp_measurePreserving hf

/-- Being an algorithm-environment sequence is invariant under pulling back along a
measure-preserving map, for measurable sequences. This is the form the `transfer` tactic uses;
`h.measurable_action` and `h.measurable_feedback` provide the side conditions when an
`IsAlgEnvSeq` hypothesis `h` is around. -/
@[transfer]
lemma _root_.MeasureTheory.MeasurePreserving.transfer_isAlgEnvSeq {𝓐 𝓨 Ω Ω' : Type*}
    [MeasurableSpace 𝓐] [MeasurableSpace 𝓨] {_ : MeasurableSpace Ω} {_ : MeasurableSpace Ω'}
    {P : Measure Ω} [IsFiniteMeasure P] {P' : Measure Ω'} [IsFiniteMeasure P'] {f : Ω' → Ω}
    (hf : MeasurePreserving f P' P) {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨}
    (hA : ∀ n, Measurable (A n)) (hY : ∀ n, Measurable (Y n)) {alg : Algorithm 𝓐 𝓨}
    {env : Environment 𝓐 𝓨} :
    IsAlgEnvSeq A Y alg env P ↔ IsAlgEnvSeq (fun n ω ↦ A n (f ω)) (fun n ω ↦ Y n (f ω)) alg env P'
    where
  mp h := h.comp_measurePreserving hf
  mpr h :=
    { measurable_action := hA
      measurable_feedback := hY
      hasLaw_action_zero := (hf.hasLaw_fun_comp_iff (hA 0)).1 h.hasLaw_action_zero
      hasCondDistrib_feedback_zero :=
        (hf.hasCondDistrib_fun_comp_iff (hA 0) (hY 0)).1 h.hasCondDistrib_feedback_zero
      hasCondDistrib_action n :=
        (hf.hasCondDistrib_fun_comp_iff (measurable_history hA hY n) (hA (n + 1))).1
          (h.hasCondDistrib_action n)
      hasCondDistrib_feedback n :=
        (hf.hasCondDistrib_fun_comp_iff ((measurable_history hA hY n).prodMk (hA (n + 1)))
          (hY (n + 1))).1 (h.hasCondDistrib_feedback n) }

namespace RDo

universe uA uY uW

variable {𝓐 : Type uA} {𝓨 : Type uY} {Ω : Type uW}
  [MeasurableSpace 𝓐] [MeasurableSpace 𝓨] [MeasurableSpace Ω]

/-- Forget the draws carried alongside each action of a traced history. -/
def forgetTrace (n : ℕ) (h : Iic n → (Ω × 𝓐) × 𝓨) : Iic n → 𝓐 × 𝓨 :=
  fun i ↦ ((h i).1.2, (h i).2)

@[fun_prop]
lemma measurable_forgetTrace (n : ℕ) :
    Measurable (forgetTrace (Ω := Ω) (𝓐 := 𝓐) (𝓨 := 𝓨) n) :=
  measurable_pi_lambda _ fun _ ↦ by unfold forgetTrace; fun_prop

omit [MeasurableSpace 𝓐] [MeasurableSpace 𝓨] [MeasurableSpace Ω] in
@[simp]
lemma forgetTrace_history {Ω₀ : Type*} {_ : MeasurableSpace Ω₀} (A : ℕ → Ω₀ → Ω × 𝓐)
    (Y : ℕ → Ω₀ → 𝓨) (n : ℕ) :
    forgetTrace n ∘ history A Y n = history (fun n ω ↦ (A n ω).2) Y n := rfl

/-- A *trace* of an algorithm: one space `Ω` of internal draws, a kernel giving their joint law at
each step given the history, and a readout reconstructing the action from them. This is what
`rdo_trace` produces for an algorithm whose policy is an `rdo` program. -/
structure AlgTrace (alg : Algorithm 𝓐 𝓨) (Ω : Type*) [MeasurableSpace Ω] where
  /-- The law of the draws the policy makes at step `n`, given the history. -/
  K : (n : ℕ) → Kernel (Iic n → 𝓐 × 𝓨) Ω
  /-- Those are Markov kernels. -/
  [markov : ∀ n, IsMarkovKernel (K n)]
  /-- The action at step `n + 1`, read off the history and the draws. -/
  out : (n : ℕ) → (Iic n → 𝓐 × 𝓨) × Ω → 𝓐
  /-- `K n` and `out n` trace the policy at step `n`. -/
  hasTrace (n : ℕ) : HasTrace (⇑(alg.policy n)) (K n) (out n)
  /-- The law of the draws made before the first action. -/
  K0 : Measure Ω
  /-- It is a probability measure. -/
  [markov0 : IsProbabilityMeasure K0]
  /-- The first action, read off those draws. -/
  out0 : Ω → 𝓐
  /-- The first readout is measurable. -/
  measurable_out0 : Measurable out0
  /-- `K0` and `out0` trace the initial distribution. -/
  map_out0 : K0.map out0 = alg.p0

attribute [instance] AlgTrace.markov AlgTrace.markov0

/-- The environment a traced algorithm interacts with: the same one, reading only the action
component of each action-with-draws. -/
def _root_.Learning.Environment.withTrace (Ω : Type*) [MeasurableSpace Ω]
    (env : Environment 𝓐 𝓨) : Environment (Ω × 𝓐) 𝓨 where
  feedback n := (env.feedback n).comap
    (fun p : (Iic n → (Ω × 𝓐) × 𝓨) × (Ω × 𝓐) ↦ (forgetTrace n p.1, p.2.2)) (by fun_prop)
  ν0 := env.ν0.comap Prod.snd measurable_snd

namespace AlgTrace

variable {alg : Algorithm 𝓐 𝓨} {env : Environment 𝓐 𝓨} (tr : AlgTrace alg Ω)

@[fun_prop]
lemma measurable_out (n : ℕ) :
    Measurable fun p : (Iic n → (Ω × 𝓐) × 𝓨) × Ω ↦ tr.out n (forgetTrace n p.1, p.2) :=
  (tr.hasTrace n).measurable_out.comp
    (((measurable_forgetTrace n).comp measurable_fst).prodMk measurable_snd)

/-- The traced algorithm: it draws the policy's internal randomness, then reads the action off it.
Its actions are pairs `(draws, action)`. -/
def algorithm : Algorithm (Ω × 𝓐) 𝓨 where
  policy n :=
    (tr.K n).comap (forgetTrace n) (by fun_prop)
      ⊗ₖ Kernel.deterministic _ (tr.measurable_out n)
  p0 := tr.K0 ⊗ₘ Kernel.deterministic tr.out0 tr.measurable_out0

/-- Comap turns a deterministic kernel into the deterministic kernel of the composite. -/
lemma _root_.ProbabilityTheory.Kernel.comap_deterministic {α β γ : Type*} [MeasurableSpace α]
    [MeasurableSpace β] [MeasurableSpace γ] {f : α → β} (hf : Measurable f) {g : γ → α}
    (hg : Measurable g) :
    (Kernel.deterministic f hf).comap g hg = Kernel.deterministic (f ∘ g) (hf.comp hg) := by
  ext c s hs
  simp [Kernel.comap_apply, Kernel.deterministic_apply]

/-- The traced policy at a given history, with the draws forgotten, is the original policy. -/
lemma map_snd_policy_apply (n : ℕ) (h : Iic n → (Ω × 𝓐) × 𝓨) :
    (tr.algorithm.policy n h).map Prod.snd = alg.policy n (forgetTrace n h) := by
  have hg : Measurable fun a ↦ tr.out n (forgetTrace n h, a) :=
    (tr.hasTrace n).measurable_out.comp (measurable_const.prodMk measurable_id)
  have hp : Measurable fun a ↦ (a, tr.out n (forgetTrace n h, a)) := measurable_id.prodMk hg
  change (((tr.K n).comap (forgetTrace n) (measurable_forgetTrace n)
    ⊗ₖ Kernel.deterministic _ (tr.measurable_out n)) h).map Prod.snd = _
  rw [Kernel.compProd_apply_eq_compProd_sectR, Kernel.sectR, Kernel.comap_deterministic,
    Measure.compProd_deterministic, Kernel.comap_apply]
  simp only [Function.comp_apply]
  rw [Measure.map_map measurable_snd hp]
  exact (tr.hasTrace n).map_eq (forgetTrace n h)

/-- Forgetting the draws of the traced policy gives back the original policy. -/
lemma snd_policy (n : ℕ) :
    (tr.algorithm.policy n).snd = (alg.policy n).comap (forgetTrace n) (by fun_prop) :=
  Kernel.ext fun h ↦ by
    rw [Kernel.snd_apply, Kernel.comap_apply, tr.map_snd_policy_apply n h]

/-- Forgetting the draws of the traced initial distribution gives back the original one. -/
lemma map_snd_p0 : tr.algorithm.p0.map Prod.snd = alg.p0 := by
  have hp : Measurable fun a ↦ (a, tr.out0 a) := measurable_id.prodMk tr.measurable_out0
  change (tr.K0 ⊗ₘ Kernel.deterministic tr.out0 tr.measurable_out0).map Prod.snd = alg.p0
  rw [Measure.compProd_deterministic, Measure.map_map measurable_snd hp, ← tr.map_out0]
  rfl

/-- `Prod.snd` of the traced initial distribution has the original law. -/
lemma hasLaw_snd_p0 : HasLaw Prod.snd alg.p0 tr.algorithm.p0 :=
  ⟨measurable_snd.aemeasurable, tr.map_snd_p0⟩

variable {Ω₀ : Type*} {_ : MeasurableSpace Ω₀} {P : Measure Ω₀} [IsProbabilityMeasure P]
  {A : ℕ → Ω₀ → Ω × 𝓐} {Y : ℕ → Ω₀ → 𝓨}

section Projection

variable (h : IsAlgEnvSeq A Y tr.algorithm (env.withTrace Ω) P)
include h

/-- **Forgetting the draws.** An algorithm-environment sequence for the traced algorithm is, after
dropping the draws from each action, one for the original algorithm. -/
lemma isAlgEnvSeq_snd : IsAlgEnvSeq (fun n ω ↦ (A n ω).2) Y alg env P where
  measurable_action n := measurable_snd.comp (h.measurable_action n)
  measurable_feedback n := h.measurable_feedback n
  hasLaw_action_zero := tr.hasLaw_snd_p0.comp h.hasLaw_action_zero
  hasCondDistrib_feedback_zero :=
    HasCondDistrib.comp_right (hf := measurable_snd) h.hasCondDistrib_feedback_zero
  hasCondDistrib_action n := by
    have h1 := (h.hasCondDistrib_action n).snd
    rw [tr.snd_policy n] at h1
    exact HasCondDistrib.comp_right (hf := measurable_forgetTrace n) h1
  hasCondDistrib_feedback n :=
    HasCondDistrib.comp_right (hf := by fun_prop) (h.hasCondDistrib_feedback n)

/-- The draws made before the first action have law `K0`. -/
lemma hasLaw_trace_zero : HasLaw (fun ω ↦ (A 0 ω).1) tr.K0 P :=
  h.hasLaw_action_zero.compProd_fst

/-- **The conditional law of the draws.** Given the history, the draws the policy makes at step
`n` are distributed as `K n` — the kernel the trace of the `rdo` program produced. -/
lemma hasCondDistrib_trace (n : ℕ) :
    HasCondDistrib (fun ω ↦ (A (n + 1) ω).1) (history (fun n ω ↦ (A n ω).2) Y n) (tr.K n) P := by
  have h1 := (h.hasCondDistrib_action n).fst
  rw [algorithm, Kernel.fst_compProd] at h1
  exact HasCondDistrib.comp_right (hf := measurable_forgetTrace n) h1

variable [MeasurableEq 𝓐]

/-- **The action is the readout of the draws.** -/
lemma action_zero_ae_eq : (fun ω ↦ (A 0 ω).2) =ᵐ[P] fun ω ↦ tr.out0 ((A 0 ω).1) := by
  refine ae_eq_of_hasCondDistrib_deterministic tr.measurable_out0 ?_ ?_ ?_
  · exact (measurable_fst.comp (h.measurable_action 0)).aemeasurable
  · exact (measurable_snd.comp (h.measurable_action 0)).aemeasurable
  · exact h.hasLaw_action_zero.compProd_snd

/-- **The action is the readout of the history and the draws.** -/
lemma action_ae_eq (n : ℕ) :
    (fun ω ↦ (A (n + 1) ω).2)
      =ᵐ[P] fun ω ↦ tr.out n (history (fun n ω ↦ (A n ω).2) Y n ω, (A (n + 1) ω).1) := by
  have hA := h.measurable_action
  have hY := h.measurable_feedback
  have h1 := (h.hasCondDistrib_action n).compProd_snd
  have h2 := ae_eq_of_hasCondDistrib_deterministic (tr.measurable_out n)
    (X := fun ω ↦ (history A Y n ω, (A (n + 1) ω).1))
    (by fun_prop) (measurable_snd.comp (h.measurable_action (n + 1))).aemeasurable h1
  exact h2

end Projection

/-- **The draws may be assumed to be there.** Any algorithm-environment sequence for `alg` and
`env` can be replaced by one on a space that also carries the algorithm's internal draws `T`, with
the same trajectory law — so anything proved about the law of the actions and feedbacks there holds
of the original. The space is existentially quantified because, by `isAlgEnvSeq_unique`, it does
not matter. -/
theorem exists_isAlgEnvSeq_trace [MeasurableEq 𝓐]
    {A₀ : ℕ → Ω₀ → 𝓐} {Y₀ : ℕ → Ω₀ → 𝓨} (h₀ : IsAlgEnvSeq A₀ Y₀ alg env P) :
    ∃ (Ω' : Type (max uA uY uW)) (_ : MeasurableSpace Ω') (P' : Measure Ω')
      (_ : IsProbabilityMeasure P') (A : ℕ → Ω' → 𝓐) (Y : ℕ → Ω' → 𝓨) (T : ℕ → Ω' → Ω),
      IsAlgEnvSeq A Y alg env P'
        ∧ P'.map (trajectory A Y) = P.map (trajectory A₀ Y₀)
        ∧ HasLaw (T 0) tr.K0 P'
        ∧ (∀ n, HasCondDistrib (T (n + 1)) (history A Y n) (tr.K n) P')
        ∧ A 0 =ᵐ[P'] (fun ω ↦ tr.out0 (T 0 ω))
        ∧ (∀ n, A (n + 1) =ᵐ[P'] fun ω ↦ tr.out n (history A Y n ω, T (n + 1) ω)) := by
  have h := IT.isAlgEnvSeq_trajMeasure tr.algorithm (env.withTrace Ω)
  refine ⟨ℕ → (Ω × 𝓐) × 𝓨, inferInstance, trajMeasure tr.algorithm (env.withTrace Ω),
    inferInstance, fun n (ω : ℕ → (Ω × 𝓐) × 𝓨) ↦ (IT.action n ω).2, IT.feedback,
    fun n (ω : ℕ → (Ω × 𝓐) × 𝓨) ↦ (IT.action n ω).1,
    tr.isAlgEnvSeq_snd h, ?_, tr.hasLaw_trace_zero h, tr.hasCondDistrib_trace h,
    tr.action_zero_ae_eq h, tr.action_ae_eq h⟩
  exact isAlgEnvSeq_unique (tr.isAlgEnvSeq_snd h) h₀

/-- **The principle behind the `alg_env_trace` tactic.** To prove a statement `motive` about an
algorithm-environment sequence it is enough to prove it on a space that also carries the
algorithm's internal draws, *provided* the statement only depends on the law of the trajectory —
which is what the `transfer` hypothesis asks for, and which is exactly the freedom
`isAlgEnvSeq_unique` gives. -/
theorem wlog_trace [MeasurableEq 𝓐]
    {motive : (Ω₀ : Type (max uA uY uW)) → [MeasurableSpace Ω₀] → (P : Measure Ω₀) →
      [IsProbabilityMeasure P] → (ℕ → Ω₀ → 𝓐) → (ℕ → Ω₀ → 𝓨) → Prop}
    (traced : ∀ (Ω' : Type (max uA uY uW)) [MeasurableSpace Ω'] (P' : Measure Ω')
        [IsProbabilityMeasure P'] (A' : ℕ → Ω' → 𝓐) (Y' : ℕ → Ω' → 𝓨) (T : ℕ → Ω' → Ω),
      IsAlgEnvSeq A' Y' alg env P' →
      HasLaw (T 0) tr.K0 P' →
      (∀ n, HasCondDistrib (T (n + 1)) (history A' Y' n) (tr.K n) P') →
      A' 0 =ᵐ[P'] (fun ω ↦ tr.out0 (T 0 ω)) →
      (∀ n, A' (n + 1) =ᵐ[P'] fun ω ↦ tr.out n (history A' Y' n ω, T (n + 1) ω)) →
      motive Ω' P' A' Y')
    (transfer : ∀ (Ω₁ : Type (max uA uY uW)) [MeasurableSpace Ω₁] (P₁ : Measure Ω₁)
        [IsProbabilityMeasure P₁] (A₁ : ℕ → Ω₁ → 𝓐) (Y₁ : ℕ → Ω₁ → 𝓨)
        (Ω₂ : Type (max uA uY uW)) [MeasurableSpace Ω₂] (P₂ : Measure Ω₂)
        [IsProbabilityMeasure P₂] (A₂ : ℕ → Ω₂ → 𝓐) (Y₂ : ℕ → Ω₂ → 𝓨),
      IsAlgEnvSeq A₁ Y₁ alg env P₁ → IsAlgEnvSeq A₂ Y₂ alg env P₂ →
      P₂.map (trajectory A₂ Y₂) = P₁.map (trajectory A₁ Y₁) →
      motive Ω₂ P₂ A₂ Y₂ → motive Ω₁ P₁ A₁ Y₁)
    :
    ∀ (Ω₀ : Type (max uA uY uW)) [MeasurableSpace Ω₀] (P : Measure Ω₀) [IsProbabilityMeasure P]
      (A : ℕ → Ω₀ → 𝓐) (Y : ℕ → Ω₀ → 𝓨), IsAlgEnvSeq A Y alg env P → motive Ω₀ P A Y := by
  intro Ω₀ _ P _ A Y h
  obtain ⟨Ω', mΩ', P', hP', A', Y', T, hseq, hlaw, hT0, hT, hA0, hA⟩ :=
    tr.exists_isAlgEnvSeq_trace h
  exact transfer Ω₀ P A Y Ω' P' A' Y' h hseq hlaw (traced Ω' P' A' Y' T hseq hT0 hT hA0 hA)

end AlgTrace


end RDo

end

end

public meta section

open Lean Lean.Meta Lean.Elab Lean.Elab.Tactic
open MeasureTheory ProbabilityTheory Learning

namespace RDo.Tactic

/-- The free variables carrying the probability space of an `IsAlgEnvSeq` hypothesis: the space,
its σ-algebra, the measure, the `IsProbabilityMeasure` instance, and the two sequences. They have
to be local hypotheses, since the tactic abstracts the goal over them. -/
def algEnvSpaceFVars (hFVar : FVarId) : MetaM (Array FVarId) := do
  let ty ← instantiateMVars (← hFVar.getType)
  unless ty.isAppOf ``IsAlgEnvSeq do
    throwError "alg_env_trace: {Expr.fvar hFVar} is not an `IsAlgEnvSeq` hypothesis"
  let as := ty.getAppArgs
  let A := as[as.size - 6]!
  let Y := as[as.size - 5]!
  let P := as[as.size - 2]!
  let mΩ := (← whnfR (← inferType P)).getAppArgs[1]!
  let Ω := (← whnfR (← inferType P)).getAppArgs[0]!
  let mut out : Array FVarId := #[]
  for e in #[Ω, mΩ, P] do
    let .fvar f := e | throwError
      "alg_env_trace: the probability space must be given by local hypotheses, but {e} is not"
    out := out.push f
  -- the `IsProbabilityMeasure` hypothesis, which `isAlgEnvSeq_unique` needs
  let some hP ← (do
    for d in ← getLCtx do
      if !d.isImplementationDetail then
        if (← instantiateMVars d.type) == (← mkAppM ``IsProbabilityMeasure #[P]) then
          return some d.fvarId
    return none) | throwError
      "alg_env_trace: no `IsProbabilityMeasure` hypothesis for {P} in the context"
  out := out.push hP
  for e in #[A, Y] do
    let .fvar f := e | throwError
      "alg_env_trace: the action and feedback sequences must be local hypotheses, but {e} is not"
    out := out.push f
  return out.push hFVar

/-- How many binders of `wlog_trace` come before its conclusion: up to and including its third
explicit argument, `transfer`. Everything after that belongs to the `∀`-shaped conclusion, which is
what the goal is unified with. -/
partial def preConclusionArity : Expr → Nat → Nat → Nat
  | .forallE _ _ b bi, n, e =>
    let e := if bi.isExplicit then e + 1 else e
    if e == 3 then n + 1 else preConclusionArity b (n + 1) e
  | _, n, _ => n

/-- Find an `IsAlgEnvSeq` hypothesis in the context. -/
def findAlgEnvSeq? : MetaM (Option FVarId) := do
  for d in ← getLCtx do
    if !d.isImplementationDetail then
      if (← instantiateMVars d.type).isAppOf ``IsAlgEnvSeq then return some d.fvarId
  return none

/-- `alg_env_trace tr` replaces an `IsAlgEnvSeq` situation by one in which the algorithm's internal
draws are present. `tr` is an `RDo.AlgTrace` for the algorithm — the trace of its policy, as
produced by `rdo_trace`.

The goal, together with every hypothesis mentioning the probability space, the measure or the two
sequences, is abstracted away from that space and two goals are left:

* `traced`: the same statement on a space that also carries the draws `T`, with `T`'s law, its
  conditional law given the history, and the equations expressing each action as the readout of the
  history and the draws;
* `transfer`: the obligation that the statement only depends on the law of the trajectory. This is
  what makes the replacement sound — the traced sequence lives on a different space, and all that
  relates it to the original is `isAlgEnvSeq_unique`.

* `alg_env_trace tr using h` names the hypothesis to use rather than searching for one.

The probability space, its σ-algebra, the measure, the `IsProbabilityMeasure` hypothesis and the
two sequences all have to be local hypotheses, since the goal is abstracted over them. -/
syntax (name := algEnvTraceTac) "alg_env_trace" ppSpace term (" using " ident)?
  (" with " (ppSpace colGt ident)+)? : tactic

elab_rules : tactic
  | `(tactic| alg_env_trace $tr $[using $h?]? $[with $names?*]?) => withMainContext do
    let g ← getMainGoal
    let hFVar ← match h? with
      | some h => getFVarId h
      | none => match ← findAlgEnvSeq? with
        | some f => pure f
        | none => throwError "alg_env_trace: no `IsAlgEnvSeq` hypothesis in the context"
    let spaceFVars ← algEnvSpaceFVars hFVar
    -- Everything else that mentions the space has to travel with the goal, or it would be lost.
    let deps ← do
      let mut deps : Array FVarId := #[]
      for d in ← getLCtx do
        if !d.isImplementationDetail && !spaceFVars.contains d.fvarId then
          let dty ← instantiateMVars d.type
          if spaceFVars.any fun f ↦ dty.containsFVar f then
            deps := deps.push d.fvarId
      pure deps
    let (_, g) ← g.revert deps
    let (_, g) ← g.revert spaceFVars (preserveOrder := true)
    -- Build `wlog_trace tr ?traced ?transfer` and check it proves the abstracted goal.
    let trE ← g.withContext do
      let e ← Term.elabTerm tr none
      Term.synthesizeSyntheticMVarsNoPostponing
      instantiateMVars e
    let (traced, transfer) ← g.withContext do
      let c ← mkConstWithFreshMVarLevels ``RDo.AlgTrace.wlog_trace
      let cty ← inferType c
      let (args, bis, concl) ← forallMetaBoundedTelescope cty (preConclusionArity cty 0 0)
      let explicits := (args.zip bis).filterMap fun (a, b) ↦ if b.isExplicit then some a else none
      unless explicits.size == 3 do
        throwError "alg_env_trace: `wlog_trace` no longer has the expected shape"
      unless ← isDefEq explicits[0]! trE do
        throwError "alg_env_trace: {trE} is not a trace of the algorithm of the hypothesis"
      unless ← isDefEq concl (← g.getType) do
        throwError "alg_env_trace: the goal does not have the expected shape{indentExpr
          (← g.getType)}"
      for (a, b) in args.zip bis do
        if b.isInstImplicit && !(← a.mvarId!.isAssigned) then
          a.mvarId!.assign (← synthInstance (← instantiateMVars (← a.mvarId!.getType)))
      g.assign (mkAppN c args)
      let traced := explicits[1]!.mvarId!
      let transfer := explicits[2]!.mvarId!
      traced.setKind .syntheticOpaque
      transfer.setKind .syntheticOpaque
      traced.setTag `traced
      transfer.setTag `transfer
      return (traced, transfer)
    -- Introduce the traced space and its properties, then whatever travelled with the goal.
    let given := (names?.map (·.map (·.getId))).getD #[]
    let defaults : Array Name := #[`Ω, `P, `A, `Y, `T, `hseq, `hT₀, `hT, `hA₀, `hA]
    let pick (i : Nat) : Name := if h : i < given.size then given[i] else defaults[i]!
    let intros : Array Name :=
      #[pick 0, `inst, pick 1, `inst, pick 2, pick 3, pick 4, pick 5, pick 6, pick 7,
        pick 8, pick 9]
    let (_, traced) ← traced.introN intros.size intros.toList
    let (_, traced) ← traced.introNP deps.size
    replaceMainGoal [traced, transfer]

end RDo.Tactic

end

@[expose] public section

open MeasureTheory ProbabilityTheory Finset Learning RDo

noncomputable section

/-! ## An example: an algorithm whose policy is an `rdo` program

A toy sequential algorithm, to show the pipeline end to end: write the policy as an `rdo` program,
get its trace from `rdo_trace`, package it as an `AlgTrace`, and then read the algorithm's internal
draws off any algorithm-environment sequence.

To do the same for `thompson` one needs the measurable equivalence between `Iic n → 𝓐 × 𝓨` and
`Vector (𝓐 × 𝓨) (n + 1)` that turns it into a policy — `Vector.v_equiv` in
`RandomDo.Tactic.Examples`, still a `sorry` there (and stated one element short). Everything after
that point is what follows below.
-/

namespace RDo.Example

variable {K : ℕ} (hK : 0 < K)

/-- The action, read off the history and the noise: depending on the sign of the noise, either
switch to arm `0` or repeat the last action. -/
def readout (n : ℕ) (p : (Iic n → Fin K × ℝ) × ℝ) : Fin K :=
  if 0 < p.2 then ⟨0, hK⟩ else (p.1 ⟨n, by simp⟩).1

@[fun_prop]
lemma measurable_readout (n : ℕ) : Measurable (readout hK n) := by
  unfold readout
  exact Measurable.ite (measurableSet_lt measurable_const measurable_snd) measurable_const
    (measurable_fst.comp ((measurable_pi_apply _).comp measurable_fst))

/-- The policy: perturb the last reward by Gaussian noise, then read the action off it. -/
def policy (n : ℕ) (h : Iic n → Fin K × ℝ) : Measure (Fin K) := rdo
  let z ← gaussianReal (h ⟨n, by simp⟩).2 1
  return readout hK n (h, z)

instance (n : ℕ) : IsMarkov (policy hK n) := by unfold policy; is_markov

/-- The noise the policy draws at step `n`, as a kernel: the one coordinate of its trace. -/
def noise (n : ℕ) : Kernel (Iic n → Fin K × ℝ) ℝ :=
  markovKernel (fun h ↦ gaussianReal (h ⟨n, by simp⟩).2 1)
    (IsMarkov.gaussianReal (by fun_prop) measurable_const)

instance (n : ℕ) : IsMarkovKernel (noise (K := K) n) := by unfold noise; infer_instance

lemma hasTrace_policy (n : ℕ) : HasTrace (policy hK n) (noise n) (readout hK n) := by
  rdo_trace (policy hK n) with h
  exact h

/-- The algorithm. -/
def alg : Algorithm (Fin K) ℝ where
  policy n := markovKernel (policy hK n) inferInstance
  p0 := Measure.dirac ⟨0, hK⟩

/-- Its trace: one Gaussian draw per step. -/
def trace : AlgTrace (alg hK) ℝ where
  K := noise
  out := readout hK
  hasTrace n := hasTrace_policy hK n
  K0 := gaussianReal 0 1
  out0 := fun _ ↦ ⟨0, hK⟩
  measurable_out0 := measurable_const
  map_out0 := by rw [Measure.map_const]; simp [alg]

/-- **The payoff.** Given any algorithm-environment sequence for this algorithm, one may assume the
space also carries the noise `Z` the policy draws at each step: it has the conditional law `noise n`
given the history, and the action is `readout` of the history and it. The trajectory keeps the same
law, so anything proved there about the actions and feedbacks holds of the original sequence. -/
theorem exists_noise (env : Environment (Fin K) ℝ) {Ω₀ : Type*} [MeasurableSpace Ω₀]
    {P : Measure Ω₀} [IsProbabilityMeasure P] {A : ℕ → Ω₀ → Fin K} {Y : ℕ → Ω₀ → ℝ}
    (h : IsAlgEnvSeq A Y (alg hK) env P) :
    ∃ (Ω' : Type) (_ : MeasurableSpace Ω') (P' : Measure Ω') (_ : IsProbabilityMeasure P')
      (A' : ℕ → Ω' → Fin K) (Y' : ℕ → Ω' → ℝ) (Z : ℕ → Ω' → ℝ),
      IsAlgEnvSeq A' Y' (alg hK) env P'
        ∧ P'.map (trajectory A' Y') = P.map (trajectory A Y)
        ∧ (∀ n, HasCondDistrib (Z (n + 1)) (history A' Y' n) (noise n) P')
        ∧ (∀ n, A' (n + 1) =ᵐ[P'] fun ω ↦ readout hK n (history A' Y' n ω, Z (n + 1) ω)) := by
  obtain ⟨Ω', mΩ', P', hP', A', Y', Z, hseq, hlaw, -, hZ, -, hA⟩ :=
    (trace hK).exists_isAlgEnvSeq_trace h
  exact ⟨Ω', mΩ', P', hP', A', Y', Z, hseq, hlaw, hZ, hA⟩

/-- **The tactic at work.** `alg_env_trace` replaces the context and the goal by ones on a space
that also carries the noise `Z` the policy draws, and leaves the obligation that the statement only
depends on the law of the trajectory. Any hypothesis mentioning the space travels with the goal, so
nothing is silently lost. -/
example (env : Environment (Fin K) ℝ) {Ω₀ : Type} [MeasurableSpace Ω₀] {P : Measure Ω₀}
    [IsProbabilityMeasure P] {A : ℕ → Ω₀ → Fin K} {Y : ℕ → Ω₀ → ℝ}
    (h : IsAlgEnvSeq A Y (alg hK) env P) :
    P.map (A 0) = Measure.dirac ⟨0, hK⟩ := by
  alg_env_trace (trace hK) with Ω P A Y Z hseq hZ₀ hZ hA₀ hA
  case traced =>
    -- `Z`, `hZ₀`, `hZ` and `hA` are the algorithm's draws and their laws, now available.
    exact hseq.hasLaw_action_zero.map_eq
  case transfer =>
    intro Ω₁ _ P₁ _ A₁ Y₁ Ω₂ _ P₂ _ A₂ Y₂ h₁ h₂ hlaw h₀
    have e₁ : A₁ 0 = (fun t ↦ (t 0).1) ∘ trajectory A₁ Y₁ := rfl
    have e₂ : A₂ 0 = (fun t ↦ (t 0).1) ∘ trajectory A₂ Y₂ := rfl
    rw [e₁, ← Measure.map_map (by fun_prop)
      (measurable_trajectory h₁.measurable_action h₁.measurable_feedback), ← hlaw,
      Measure.map_map (by fun_prop)
        (measurable_trajectory h₂.measurable_action h₂.measurable_feedback), ← e₂, h₀]

/-- **`extend_space` alongside an algorithm-environment sequence.** After the extension, `Ω`, `P`,
`A` and `Y` live on a larger space that also carries a Gaussian `U` independent of the whole
trajectory, and `h` has been transported by `IsAlgEnvSeq.comp_measurePreserving`. The statement
does not mention the original space, so the `transfer` obligation is trivial and `extend_space`
closes it. The measurability of the sequence is put in the context first, so that the
independence statement `hind` covers `A` and `Y`. -/
example (env : Environment (Fin K) ℝ) {Ω₀ : Type} [MeasurableSpace Ω₀] {P : Measure Ω₀}
    [IsProbabilityMeasure P] {A : ℕ → Ω₀ → Fin K} {Y : ℕ → Ω₀ → ℝ}
    (h : IsAlgEnvSeq A Y (alg hK) env P) :
    ∃ (Ω' : Type) (_ : MeasurableSpace Ω') (P' : Measure Ω') (_ : IsProbabilityMeasure P')
      (A' : ℕ → Ω' → Fin K) (Y' : ℕ → Ω' → ℝ) (U : Ω' → ℝ),
      IsAlgEnvSeq A' Y' (alg hK) env P' ∧ HasLaw U (gaussianReal 0 1) P'
        ∧ IndepFun (trajectory A' Y') U P' := by
  have hA := h.measurable_action
  have hY := h.measurable_feedback
  extend_space! (gaussianReal 0 1) using P with U hU hind
  have hAY : IndepFun (trajectory A Y) U P :=
    hind.comp (φ := fun (p : (ℕ → Fin K) × (ℕ → ℝ)) (n : ℕ) ↦ (p.1 n, p.2 n)) (by fun_prop)
      measurable_id
  exact ⟨Ω₀, inferInstance, P, inferInstance, A, Y, U, h, hU, hAY⟩

/-- **The explicit form, `extend_space_map`.** The goal mentions the space through `P` and `A 0`;
`transfer` moves it to the new space, with the measurability of the sequence taken from `h`. In
the extended goal, `transfer hf at h` pulls the sequence back. -/
example (env : Environment (Fin K) ℝ) {Ω₀ : Type} [MeasurableSpace Ω₀] {P : Measure Ω₀}
    [IsProbabilityMeasure P] {A : ℕ → Ω₀ → Fin K} {Y : ℕ → Ω₀ → ℝ}
    (h : IsAlgEnvSeq A Y (alg hK) env P) :
    P.map (A 0) = Measure.dirac ⟨0, hK⟩ := by
  have hA := h.measurable_action
  have hY := h.measurable_feedback
  extend_space_map (gaussianReal 0 1) with Ω' P' f hf U hU hind
  transfer hf at h
  exact h.hasLaw_action_zero.map_eq

end RDo.Example

end

end
